# Generated by Django 6.0.5 on 2026-05-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='orden',
            field=models.IntegerField(default=0, help_text='Número para ordenar (menor primero)'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='publicado',
            field=models.BooleanField(default=True, help_text='Mostrar en el blog'),
        ),
    ]
