# Generated by Django 6.0.5 on 2026-05-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_articulo_orden_alter_articulo_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagenes_extra',
            field=models.TextField(blank=True, default='[]', help_text='Lista de rutas en formato JSON (ej: ["/media/blog/img1.jpg", "/media/blog/img2.jpg"])'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagen destacada'),
        ),
    ]
