# Generated by Django 6.0.4 on 2026-05-07 09:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50, unique=True)),
                ('localidad', models.CharField(max_length=200)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('como_nos_conocio', models.CharField(blank=True, max_length=200)),
                ('cantidad_compras', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('PYG', 'Guaraníes'), ('USD', 'Dólares'), ('EUR', 'Euros'), ('ARS', 'Pesos Argentinos'), ('BRL', 'Reales Brasileños')], default='PYG', max_length=3)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_pedido', models.CharField(blank=True, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', '🟡 Pendiente (esperando pago)'), ('pagado', '🔵 Pagado (preparando envío)'), ('enviado', '🟣 Enviado (en camino)'), ('completado', '✅ Completado (entregado)'), ('cancelado', '❌ Cancelado')], default='pendiente', max_length=20)),
                ('origen', models.CharField(choices=[('web', '🌐 Web'), ('instagram', '📷 Instagram'), ('whatsapp', '💬 WhatsApp'), ('presencial', '🏪 Presencial')], default='web', max_length=20)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('moneda', models.CharField(choices=[('PYG', 'Guaraníes'), ('USD', 'Dólares'), ('EUR', 'Euros'), ('ARS', 'Pesos Argentinos'), ('BRL', 'Reales Brasileños')], default='PYG', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('contra_entrega', 'Contra entrega')], max_length=20)),
                ('metodo_entrega', models.CharField(blank=True, choices=[('retiro', 'Retiro en persona'), ('delivery', 'Delivery'), ('correo', 'Envío por correo')], max_length=20)),
                ('empresa_transporte', models.CharField(blank=True, max_length=100)),
                ('se_envio', models.BooleanField(default=False)),
                ('facturado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.cliente')),
                ('productos', models.ManyToManyField(through='ventas.DetalleVenta', to='productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta'),
        ),
    ]
