# Generated by Django 6.0.4 on 2026-05-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='PYG', max_length=3)),
                ('periodo', models.CharField(help_text='Ej: mensual, trimestral, anual', max_length=50)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Costo Fijo',
                'verbose_name_plural': 'Costos Fijos',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='PYG', max_length=3)),
                ('tipo', models.CharField(choices=[('insumo', 'Compra de insumos (cobre, materiales)'), ('envio', 'Gastos de envío'), ('comision', 'Comisiones (Payoneer, Creala)'), ('fijo', 'Gasto fijo (alquiler, internet, luz)'), ('imprevisto', 'Gasto imprevisto'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='PYG', max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingreso', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha'],
            },
        ),
    ]
