# Generated by Django 6.0.4 on 2026-05-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del producto')),
                ('stock', models.IntegerField(default=0, help_text='Stock disponible')),
                ('stock_minimo', models.IntegerField(default=5, help_text='Stock mínimo para alerta')),
                ('precio_pyg', models.DecimalField(decimal_places=0, default=0, help_text='Precio en Guaraníes', max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(choices=[('USD', 'Dólar Americano'), ('EUR', 'Euro'), ('ARS', 'Peso Argentino'), ('BRL', 'Real Brasileño')], max_length=3, unique=True)),
                ('tasa', models.DecimalField(decimal_places=2, help_text='Ej: 7500 = 1 USD = 7500 PYG', max_digits=12)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
