# Generated by Django 6.0.4 on 2026-05-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('vasos', 'Vasos'), ('botellas', 'Botellas'), ('pulseras', 'Pulseras'), ('anillos', 'Anillos'), ('brazaletes', 'Brazaletes'), ('cadenas', 'Cadenas'), ('aros', 'Aros'), ('diademas', 'Diademas'), ('tobilleras', 'Tobilleras'), ('limpia_lengua', 'Limpia lengua'), ('dispenser', 'Dispenser de agua'), ('jarra', 'Jarra'), ('piramides', 'Pirámides'), ('espirales_mano', 'Espirales de mano'), ('pendulos', 'Péndulos'), ('energizador_agua', 'Energizador de agua')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Mostrar en la página principal'),
        ),
    ]
