# Generated by Django 6.0.4 on 2026-05-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_categoria_producto_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_vertical',
            field=models.BooleanField(default=False, help_text='Marca esta casilla si la imagen es más alta que ancha (Ej: botellas, jarras)', verbose_name='Imagen vertical (alta)'),
        ),
    ]
