# Generated by Django 6.0.5 on 2026-05-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_es_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='orden',
            field=models.IntegerField(default=0, help_text='Número de orden (menor = más arriba)'),
        ),
    ]
